apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cc-ingress
  namespace: cc-frontend
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/subnets: subnet-039e4abf1eb4dd567,subnet-0808ff1863bf046da

spec:
  rules:
    - host: ch-jeon.store
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cc-nginx-svc
                port:
                  number: 80

